Repository department-of-veterans-affairs/content-build, pull requests merged in 2021-06, with the labels that each got.

#203 Add expand image button to show more items
  src/site/layouts/media_list_images.drupal.liquid
Labels: VSA, front-end

#207 NOD: build in prod
  src/applications/registry.json
Labels: VSA, front-end

#209 Fix pagination styling on outreach mats
  src/site/layouts/publication_listing.drupal.liquid
Labels: VSA, front-end

#220 Update how do you rate with submit button
  src/site/includes/how-do-you-rate.drupal.liquid
Labels: VSA, front-end

#202 Vet center expandable alert
  src/site/includes/vet_centers/address_phone_image.liquid
  src/site/layouts/vet_center.drupal.liquid
  src/site/layouts/vet_center_locations_list.drupal.liquid
  src/site/stages/build/drupal/graphql/vetCenter.graphql.js
  src/site/stages/build/drupal/graphql/vetCenterLocations.graphql.js
Labels: VSA, front-end, vet-center

#226 Update how do you rate component with a11y improvements
  src/site/includes/how-do-you-rate.drupal.liquid
Labels: VSA, front-end

#229 Fix - On this page navigation should have a unique accessible label
  src/site/layouts/vet_center.drupal.liquid
Labels: VSA, front-end, vet-center

#242 Fix - Not all locations are included on the VAMC Locations page
  src/site/stages/build/drupal/graphql/facilities-fragments/healthCareLocalFacility.node.graphql.js
Labels: VSA, front-end, vamc-facilites

#232 Update FSR link as well as breadcrumbs
  src/applications/registry.json
Labels: enhancement, front-end, vsa-benefits-2

#250 Update incorrect breadcrumb link
  src/applications/registry.json
Labels: bug, front-end, vsa-benefits-2

#254 Tweak how do you rate component styling
  src/site/includes/how-do-you-rate.drupal.liquid
Labels: VSA, front-end

#249 Stories page is preview-able
  .liquidrc
  src/site/filters/liquid.js
  src/site/layouts/story_listing.drupal.liquid
  src/site/stages/build/drupal/graphql/GetLatestPageById.graphql.js
Labels: front-end, vamc-facilites

#259 Bump how do you rate to prod
  src/site/includes/how-do-you-rate.drupal.liquid
Labels: VSA, front-end

#253 News release page now preview-able
  src/site/filters/liquid.js
  src/site/filters/liquid.unit.spec.js
  src/site/layouts/event_listing.drupal.liquid
  src/site/layouts/press_releases_listing.drupal.liquid
  src/site/layouts/tests/vamc/fixtures/pressReleasesMockData.json
  src/site/stages/build/drupal/graphql/GetLatestPageById.graphql.js
Labels: front-end, vamc-facilites

#265 Update h4 to h3
  src/site/layouts/home.drupal.liquid
Labels: VSA, front-end

#281 Hide map from screenreader in Vet Center
  src/site/includes/image_and_static_map.liquid
Labels: VSA, front-end, vet-center, vsa-facilities

#284 Fix clp stories images
  src/site/layouts/campaign_landing_page.drupal.liquid
Labels: VSA, front-end

#269 Make images optional on VAMC pages (Main, Location, News Stories)
  script/preview.js
  src/platform/utilities/data/clone.js
  src/platform/utilities/data/cloneDeep.js
  src/site/components/image.drupal.liquid
  src/site/components/tests/image.drupal.unit.spec.js
  src/site/includes/facilityListing.drupal.liquid
  src/site/includes/tests/facilityListing.drupal.unit.spec.js
  src/site/layouts/news_story.drupal.liquid
  src/site/teasers/news_story.drupal.liquid
  src/site/teasers/news_story_page.drupal.liquid
  src/site/teasers/news_story_page_feature.drupal.liquid
Labels: VSA, front-end, vamc-facilites, vsa-facilities

#285 Removed intro text in Vet Center locations page
  src/site/layouts/vet_center_locations_list.drupal.liquid
Labels: front-end, vet-center, vsa-facilities

#289 Add blocklisted-from-prod entities functionality
  src/site/constants/blocklistedEntities.js
  src/site/stages/build/plugins/create-environment-filter.js
Labels: VSA, front-end

#290 Tweak CLP styling
  src/site/layouts/campaign_landing_page.drupal.liquid
Labels: VSA, front-end

#299 Update alt with aria-label
  src/site/layouts/campaign_landing_page.drupal.liquid
Labels: VSA, front-end

#301 Formatting metatags template
  src/site/includes/metatags.drupal.liquid
  src/site/includes/metatags.liquid
Labels: VSA, front-end

#297 Added data layer to VAMC featured content links
  .github/CODEOWNERS
  src/site/layouts/health_care_local_facility.drupal.liquid
  src/site/layouts/health_care_region_page.drupal.liquid
  src/site/layouts/liquid_template_axe_check_smoke_test.drupal.liquid
  src/site/paragraphs/facilities/list_of_link_teasers_facility.drupal.liquid
  src/site/paragraphs/list_of_link_teasers_facility.drupal.liquid
Labels: front-end, vamc-facilites, vsa-facilities

#307 Use optionLabel over event.target.value
  src/site/includes/how-do-you-rate.drupal.liquid
Labels: VSA, front-end
