Repository department-of-veterans-affairs/content-build, pull requests merged in 2021-11, with the labels that each got.

#498 Github Actions (daily-deploy & content-release) -- Enable daily deploy in github action for prod
  .github/workflows/content-release.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/daily-deploy-production.yml
  Jenkinsfile
  script/github-actions/check-broken-links.js
Labels: Do not merge

#741 Add stdized red color to VCL
  src/site/includes/top-nav.html
Labels: front-end, VSA

#743 Add ID to common va-accordion-item
  src/site/paragraphs/collapsible_panel.drupal.liquid
Labels: enhancement, front-end, VSA

#754 Add events widget to event_listing
  src/site/layouts/event_listing.drupal.liquid
Labels: front-end, VSA

#763 Add pastEvents and allEventTeasers to window
  src/site/layouts/event_listing.drupal.liquid
Labels: front-end, VSA

#764 Update hashReference filter
  src/site/filters/liquid.js
  src/site/filters/liquid.unit.spec.js
  src/site/paragraphs/collapsible_panel.drupal.liquid
Labels: enhancement, front-end, VSA

#785 Remove skipped e2e tests
  src/site/layouts/tests/vamc/e2e/commands.cypress.js
  src/site/layouts/tests/vamc/e2e/events.cypress.spec.js
  src/site/layouts/tests/vamc/e2e/health_service_detail_page.cypress.spec.js
  src/site/layouts/tests/vamc/e2e/location_detail.cypress.spec.js
  src/site/layouts/tests/vamc/e2e/location_home.cypress.spec.js
  src/site/layouts/tests/vamc/e2e/system_home.cypress.spec.js
  src/site/layouts/tests/vamc/fixtures/mock-facility-data-v1.json
Labels: front-end, VSA
