Repository department-of-veterans-affairs/content-build, pull requests merged in 2021-08, with the labels that each got.

#416 Add hostUrl prefix to og:image custom metatags
  src/site/includes/metatags.drupal.liquid
Labels: VSA, front-end

#432 Fix spelling error on variable assignment
  src/site/paragraphs/downloadable_file.drupal.liquid
Labels: front-end, VSA

#436 Updated filterUpcomingEvents test
  src/site/filters/liquid.unit.spec.js
Labels: front-end, vsa-facilities

#437 Use h2 for alert heading for a11y
  src/site/includes/alerts.drupal.liquid
  src/site/includes/tests/alerts.drupal.unit.spec.js
  src/site/includes/tests/fixtures/alerts.json
Labels: front-end, VSA

#463 Fix HLR breadcrumb
  src/applications/registry.json
Labels: front-end, VSA

#464 [28401] Prevent No Commit Pushes to Origin
  .husky/pre-push
  script/pre-push.sh
Labels: enhancement, front-end

#485 Support new <Banner /> component
  src/site/includes/header.html
Labels: front-end, VSA

#488 Update footer
  src/platform/static-data/footer-links.json
Labels: front-end, VSA
