Repository department-of-veterans-affairs/content-build, pull requests merged in 2021-05, with the labels that each got.

#116 Fix quotes in sidebar data on person_profile pages.
  src/site/layouts/person_profile.drupal.liquid
Labels: vamc-facilites

#100 Implement VAMC data layer for links within accordions
  src/site/facilities/health_service.drupal.liquid
  src/site/layouts/health_services_listing.drupal.liquid
Labels: VSA, front-end, vamc-facilites

#121 Add mainEntity itemprop
  src/site/layouts/page.drupal.liquid
Labels: VSA, front-end

#134 Remove top padding
  src/site/layouts/campaign_landing_page.drupal.liquid
Labels: VSA, front-end

#125 Vet center content fixes
  src/site/includes/vet_center_address_phone_image.liquid
  src/site/includes/vet_center_health_services.liquid
  src/site/includes/vet_center_services.liquid
  src/site/layouts/tests/vet_center/vet_center.drupal.unit.spec.js
  src/site/layouts/vet_center.drupal.liquid
  src/site/layouts/vet_center_locations_list.drupal.liquid
Labels: VSA, vet-center, vsa-facilities

#142 Remove extra wrapping div for extra categories
  src/site/paragraphs/lists_of_links.drupal.liquid
Labels: VSA, front-end

#139 Add data layer for Vet centers
  src/site/includes/image_and_static_map.liquid
  src/site/includes/vet_center_address_phone_image.liquid
  src/site/layouts/vet_center.drupal.liquid
  src/site/layouts/vet_center_locations_list.drupal.liquid
  src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js
Labels: VSA, front-end, vet-center

#166 Vet center css fixes
  src/site/includes/vet_center_address_phone_image.liquid
Labels: front-end, vet-center, vsa-facilities

#160 Update how do you rate component
  src/site/includes/how-do-you-rate.drupal.liquid
Labels: VSA, front-end

#175 Conditionally render cta link
  src/site/layouts/campaign_landing_page.drupal.liquid
Labels: VSA, front-end

#189 Fix breadcrumb path
  src/applications/registry.json
Labels: VSA, bug

#194 Remove random-lang-support-link from prod builds
  src/site/stages/build/plugins/create-environment-filter.js
Labels: VSA, front-end

#199 Add conditional rendering check for clp video cta
  src/site/layouts/campaign_landing_page.drupal.liquid
Labels: VSA, front-end
