Repository department-of-veterans-affairs/content-build, pull requests merged in 2021-07, with the labels that each got.

#311 Update footer link
  src/platform/static-data/footer-links.json
Labels: VSA, front-end

#312 Update hero image derivative
  src/site/layouts/campaign_landing_page.drupal.liquid
  src/site/stages/build/drupal/graphql/nodeCampaignLandingPage.graphql.js
Labels: VSA, front-end

#313 Restore HREF's to In the Spotlight links on VAMC pages
  src/site/layouts/tests/vamc/system_home.cypress.spec.js
  src/site/paragraphs/facilities/list_of_link_teasers_facility.drupal.liquid
Labels: vamc-facilites

#315 Add mobile vet centers to locations page
  src/site/includes/vet_centers/address_phone_image.liquid
  src/site/layouts/vet_center_locations_list.drupal.liquid
Labels: front-end, vet-center, vsa-facilities

#276 Fix - Change hardcoded Leadership menu link, check cms feature flag
  src/site/filters/liquid.js
  src/site/layouts/person_profile.drupal.liquid
Labels: VSA, front-end, vamc-facilites, vsa-facilities

#347 Remove pittsburgh title edge case
  src/site/includes/metatags.drupal.liquid
Labels: VSA, front-end

#358 Move content id from top section to main
  src/site/layouts/home.drupal.liquid
  src/site/layouts/home.html
  src/site/layouts/tests/home/fixtures/home.json
  src/site/layouts/tests/home/home.unit.spec.js
Labels: VSA, front-end

#378 Replace usa-accordion with va-accordion
  src/site/facilities/facility_health_service.drupal.liquid
  src/site/facilities/health_service.drupal.liquid
  src/site/layouts/campaign_landing_page.drupal.liquid
  src/site/layouts/faq_multiple_q_a.drupal.liquid
  src/site/layouts/health_care_local_facility.drupal.liquid
  src/site/layouts/tests/vamc/location_home.cypress.spec.js
  src/site/navigation/facility_no_drupal_page_sidebar_nav.drupal.liquid
  src/site/paragraphs/collapsible_panel.drupal.liquid
  src/site/paragraphs/q_a.collapsible_panel.drupal.liquid
Labels: VSA, front-end

#395 update last mod date
  src/site/stages/build/plugins/create-sitemaps.js
Labels: VSA

#394 Wrap footer in role=contentinfo section for consistent landmarks
  src/site/includes/footer.html
  src/site/includes/header.html
Labels: VSA, front-end

#399 Fix runtime error on external domains
  src/site/layouts/home.html
Labels: VSA, front-end

#397 Add type to pdf file download links
  src/site/filters/liquid.js
  src/site/filters/liquid.unit.spec.js
  src/site/layouts/publication_listing.drupal.liquid
  src/site/layouts/tests/publication_listing/fixtures/docxFileData.json
  src/site/layouts/tests/publication_listing/fixtures/pdfFileData.json
  src/site/layouts/tests/publication_listing/publication_listing.drupal.unit.spec.js
  src/site/paragraphs/downloadable_file.drupal.liquid
Labels: VSA, front-end

#392 Combine metatags templates into one
  src/site/includes/header.html
  src/site/includes/metatags.drupal.liquid
  src/site/includes/metatags.liquid
  src/site/includes/tests/metatags.drupal.unit.spec.js
  src/site/layouts/basic_landing_page.drupal.liquid
  src/site/layouts/bios_page.drupal.liquid
  src/site/layouts/campaign_landing_page.drupal.liquid
  src/site/layouts/checklist.drupal.liquid
  src/site/layouts/event.drupal.liquid
  src/site/layouts/event_listing.drupal.liquid
  src/site/layouts/events_page.drupal.liquid
  src/site/layouts/faq_multiple_q_a.drupal.liquid
  src/site/layouts/health_care_facility_status.drupal.liquid
  src/site/layouts/health_care_local_facility.drupal.liquid
  src/site/layouts/health_care_region_detail_page.drupal.liquid
  src/site/layouts/health_care_region_locations_page.drupal.liquid
  src/site/layouts/health_care_region_page.drupal.liquid
  src/site/layouts/health_services_listing.drupal.liquid
  src/site/layouts/home.drupal.liquid
  src/site/layouts/landing_page.drupal.liquid
  src/site/layouts/leadership_listing.drupal.liquid
  src/site/layouts/liquid_template_axe_check_smoke_test.drupal.liquid
  src/site/layouts/media_list_images.drupal.liquid
  src/site/layouts/media_list_videos.drupal.liquid
  src/site/layouts/news_stories_page.drupal.liquid
  src/site/layouts/news_story.drupal.liquid
  src/site/layouts/office.drupal.liquid
  src/site/layouts/page.drupal.liquid
  src/site/layouts/person_profile.drupal.liquid
  src/site/layouts/press_release.drupal.liquid
  src/site/layouts/press_releases_listing.drupal.liquid
  src/site/layouts/press_releases_page.drupal.liquid
  src/site/layouts/publication_listing.drupal.liquid
  src/site/layouts/q_a.drupal.liquid
  src/site/layouts/step_by_step.drupal.liquid
  src/site/layouts/story_listing.drupal.liquid
  src/site/layouts/support_resources_article_listing.drupal.liquid
  src/site/layouts/support_resources_detail_page.drupal.liquid
  src/site/layouts/va_form.drupal.liquid
  src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid
  src/site/layouts/vamc_system_policies_page.drupal.liquid
  src/site/layouts/vet_center.drupal.liquid
  src/site/layouts/vet_center_locations_list.drupal.liquid
Labels: VSA, front-end
