Repository department-of-veterans-affairs/content-build, pull requests merged in 2022-02, with the labels that each got.

#956 update pges from staging review
  src/site/layouts/event.drupal.liquid
  src/site/layouts/event_listing.drupal.liquid
  src/site/layouts/events_page.drupal.liquid
Labels: front-end, VSA

#955 DNM: VAGOV-0000: add p-retry package, use to do retries on individual queries with bad responses.
  package.json
  src/site/stages/build/drupal/api.js
  yarn.lock
Labels: Do not merge

#680 VACMS-1317: Update logic to use order field instead of featured field.
  src/site/layouts/event_listing.drupal.liquid
  src/site/layouts/news_stories_page.drupal.liquid
  src/site/layouts/story_listing.drupal.liquid
  src/site/layouts/vet_center.drupal.liquid
  src/site/stages/build/drupal/graphql/facilities-fragments/healthCareRegionEvents.node.graphql.js
  src/site/stages/build/drupal/graphql/facilities-fragments/healthCareRegionNewsStories.node.graphql.js
  src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js
  src/site/stages/build/drupal/graphql/nodeEvent.graphql.js
  src/site/stages/build/drupal/graphql/storyListingPage.graphql.js
Labels: front-end
