Repository department-of-veterans-affairs/content-build, pull requests merged in 2022-04, with the labels that each got.

#1074 Add blue left arrow
  src/site/assets/img/arrow-left-blue.svg
Labels: enhancement, front-end

#1061 Add mock details page
  src/applications/registry.json
Labels: enhancement, user story, front-end

#1080 VAVSA-39436: Replace old office hours field with new one.
  src/site/facilities/vha_facility_nonclinical_service.drupal.liquid
  src/site/filters/fixtures/healthCareRegionNonClinicalServicesData.json
  src/site/filters/liquid.js
  src/site/filters/liquid.unit.spec.js
  src/site/includes/hours.liquid
  src/site/includes/vet_centers/address_phone_image.liquid
  src/site/includes/vet_centers/hours.liquid
  src/site/includes/vet_centers/hours_dynamic.liquid
  src/site/layouts/health_care_local_facility.drupal.liquid
  src/site/layouts/tests/vet_center/template/fixtures/vet_center_data.json
  src/site/layouts/vet_center.drupal.liquid
  src/site/paragraphs/service_hours.drupal.liquid
  src/site/paragraphs/service_location.drupal.liquid
  src/site/stages/build/drupal/graphql/facilities-fragments/healthCareLocalFacility.node.graphql.js
  src/site/stages/build/drupal/graphql/facilities-fragments/healthCareRegionNonClinicialServices.node.graphql.js
  src/site/stages/build/drupal/graphql/healthCareLocalFacilityPage.graphql.js
  src/site/stages/build/drupal/graphql/paragraph-fragments/serviceLocation.paragraph.graphql.js
Labels: vsa-facilities

#1088 VAVSA-37366: Add remaining spec items to billing tpl.
  src/site/facilities/vha_facility_nonclinical_services.drupal.liquid
  src/site/includes/hours-item.liquid
  src/site/includes/hours.liquid
  src/site/layouts/vamc_system_billing_insurance.drupal.liquid
  src/site/stages/build/drupal/graphql/vamcBillingAndInsurancePage.graphql.js
Labels: vsa-facilities

#1082 VAVSA-37367: Add toc, facility name and links to facility
  src/site/includes/centralized-content.drupal.liquid
  src/site/layouts/vamc_system_register_for_care.drupal.liquid
  src/site/paragraphs/service_location.drupal.liquid
Labels: vsa-facilities

#1103 Do not merge: Revert "Fix s3 bucket URLs referenced by CMS preview server"
  script/preview.js
Labels: Do not merge
