Repository department-of-veterans-affairs/content-build, pull requests merged in 2023-08, with the labels that each got.

#1650 VACMS-11354 Add IDs to accordions
  src/site/facilities/facility_health_service.drupal.liquid
  src/site/facilities/health_service.drupal.liquid
  src/site/layouts/campaign_landing_page.drupal.liquid
  src/site/layouts/faq_multiple_q_a.drupal.liquid
  src/site/layouts/health_care_local_facility.drupal.liquid
  src/site/layouts/landing_page.drupal.liquid
  src/site/paragraphs/q_a.collapsible_panel.drupal.liquid
Labels: Do not merge

#1656 VACMS-14541: Add Reusable QAs component for R&S detail pages
  src/site/layouts/support_resources_detail_page.drupal.liquid
  src/site/paragraphs/q_a_group_content.drupal.liquid
Labels: ready for review

#1668 VACMS-14697 Use footer label instead of description to populate footer titles
  .github/workflows/close-stale-pull-requests.yml
  src/site/stages/build/drupal/menus.js
  src/site/stages/build/plugins/create-header-footer.js
  src/site/stages/build/plugins/tests/create-header-footer.unit.spec.js
Labels: Do not merge

#1684 Add appeals testing app
  src/applications/registry.json
Labels: front-end, benefits-team-1
