Repository department-of-veterans-affairs/content-build, pull requests merged in 2024-03, with the labels that each got.

#1940 Update Pensions breadcrumb title
  src/applications/registry.json
Labels: pension-benefits

#1953 77329 - [CDP] - Deprecate legacy applications
  src/applications/registry.json
Labels: front-end, vsa-benefits-2

#1990 NDBEX 63351: Added breadcrumb
  src/applications/registry.json
Labels: burial-benefits
