Repository department-of-veterans-affairs/content-build, pull requests merged in 2024-08, with the labels that each got.

#2219 DR | Wrap RUM init in window load
  src/site/includes/decision-reviews-rum.html
Labels: Decision-Reviews-Team

#2223 Fix DR testing paths & add new SC testing app
  src/applications/registry.json
Labels: front-end, Decision-Reviews-Team

#2247 Medallia - Add feedback button to checklist page layout
  src/site/layouts/checklist.drupal.liquid
Labels: medallia
