Repository department-of-veterans-affairs/content-build, pull requests merged in 2025-09, with the labels that each got.

#2634 DMT | Update manage dependents breadcrumb text
  src/applications/registry.json
Labels: dependents-benefits

#2640 MBMS-102590 ToN form
  src/applications/registry.json
Labels: mbs-self-service

#2652 init(21-2680): Add 21-2680 House Bound Status
  src/applications/registry.json
Labels: benefits-optimization, benefits-optimization-aquia

#2657 init(21-4192): Add application for employment information
  src/applications/registry.json
Labels: benefits-optimization, benefits-optimization-aquia

#2658 init(21a-530a): Add application for interment allowance
  src/applications/registry.json
Labels: benefits-optimization, benefits-optimization-aquia
